# action.yml
name: 'Check DCO Signoff'
description: 'A reusable action that checks if all commit has a DCO signoff'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run Python script
      run: python dco_check.py
      shell: bash
